// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByo_KsTsbFBy9-ZFQ6ZbxXnROavf7ORhc',
    appId: '1:800914358702:web:2e017121f5184dcad7c83f',
    messagingSenderId: '800914358702',
    projectId: 'bayea-1f089',
    authDomain: 'bayea-1f089.firebaseapp.com',
    storageBucket: 'bayea-1f089.appspot.com',
    measurementId: 'G-0PGD2Q5FC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhQ_fWvsIoMTeNUXV6n0kFN5rTjFDfKuE',
    appId: '1:800914358702:android:4109e14c09597b5cd7c83f',
    messagingSenderId: '800914358702',
    projectId: 'bayea-1f089',
    storageBucket: 'bayea-1f089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJwZW3OIMhVeS8SVQrBp5igZ7k0o1jR4',
    appId: '1:800914358702:ios:61787eca4f658847d7c83f',
    messagingSenderId: '800914358702',
    projectId: 'bayea-1f089',
    storageBucket: 'bayea-1f089.appspot.com',
    iosClientId: '800914358702-r55be39dgd994901dqdb8mo17b79trvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJwZW3OIMhVeS8SVQrBp5igZ7k0o1jR4',
    appId: '1:800914358702:ios:61787eca4f658847d7c83f',
    messagingSenderId: '800914358702',
    projectId: 'bayea-1f089',
    storageBucket: 'bayea-1f089.appspot.com',
    iosClientId: '800914358702-r55be39dgd994901dqdb8mo17b79trvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
